### ISSUE TITLE
Add no-floating-promises as default rule

### ISSUE THREAD

**Issue by yamadayuki** [wantedly/frolint#110]
## WHY & WHAT

We can now use the [`no-floating-promises`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md)
https://github.com/typescript-eslint/typescript-eslint/pull/495

> This rule forbids usage of Promise-like values in statements without handling their errors appropriately. Unhandled promises can cause several issues, such as improperly sequenced operations, ignored Promise rejections and more. Valid ways of handling a Promise-valued statement include awaiting, returning, and either calling .then() with two arguments or .catch() with one argument

How do you think about this?
@KentoMoriwaki @chloe463 @kobayang

**Comment by KentoMoriwaki** [comment]
I want this rule enabled by default. 

It is very useful especially when writing tests which including async functions. 
For example, this test will pass even when it does not include the text("Some Text") because this sentence returns a unhandled promise. 

```
// Should put `await` head
expect(waitForText("Some Text")).resolves.toBeTruthy();
```

**Comment by kobayang** [comment]
Sounds good to me.

**Comment by yamadayuki** [comment]
OK, I'll create PR to add the `no-floating-promises` rule as default.
