### ISSUE TITLE
Conflicting rules between eslint and prettier

### ISSUE THREAD

**Issue by chloe463** [wantedly/frolint#31]
## Why & What

I think the following rules are conflicting between eslint and prettier.

- `space-before-function-paren`
  - eslint says space is required, prettier says 'no' on the other hand.
- `comma-dangle`
  - eslint says trailing comma is required, prettier says 'no'

😕 

I found only two conflict rules so far, but maybe some more...? (I will report if I find some)

**Comment by yamadayuki** [comment]
Please tell me examples of what the code has conflicts.

**Comment by chloe463** [comment]
```typescript
export const hoge = (foo: number) => {
  return function () {  // Here
    return {
      foo,
      bar: "bar",  // and here
    };
  };
};
```

Maybe `.prettierrc` fixes this issue...?

**Comment by yamadayuki** [comment]
Is it notified from `frolint`? I cannot reproduce the errors with your minimum code. I supposed that your conflicts are produced by the editor with ESLint / Prettier extensions.

`space-before-function-paren`'s rule is below. So ESLint requires the space only async arrow function, and it has no conflict against prettier.

```
"space-before-function-paren": Array [
  "warn",
  Object {
    "anonymous": "never",
    "asyncArrow": "always",
    "named": "never",
  },
],
```

`comma-dangle`'s rule is below. ESLint requires the last comma for array, export, import, object. We prohibit the function arguments comma dangling. It is compatible with the prettier's `"trailingComma": "es5"` option, so we have no conflict.

```
"comma-dangle": Array [
  "error",
  Object {
    "arrays": "always-multiline",
    "exports": "always-multiline",
    "functions": "never",
    "imports": "always-multiline",
    "objects": "always-multiline",
  },
],
```

**Comment by chloe463** [comment]
You're right.
My vscode eslint plugin setting causes the problem.
Turning `Eslint: Auto Fix On Save` on solves this issue.
Thanks!

**Comment by srk1195** [comment]
Hey, even after your suggestions I am hitting the problem. I added the below config to settings.json on vscode.
` "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },`
Still I am getting the issue.

**Comment by yamadayuki** [comment]
> Hey, even after your suggestions I am hitting the problem. I added the below config to settings.json on vscode.
> 
> ` "editor.codeActionsOnSave": {
> 
>     "source.fixAll.eslint": true
> 
>   },`
> 
> Still I am getting the issue.

@srk1195 Could you paste your .eslintrc and .prettierrc? If you use the frolint section in package.json, plz paste the frolint section in package.json.
And then, let me see your settings for VSCode's rslint settings

**Comment by srk1195** [comment]
Hey @yamadayuki,

**.eslintrc.js**
`module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es2020: true,
  },
  extends: ['airbnb-base'],
  parserOptions: {
    ecmaVersion: 11,
  },
  rules: {},
};
`
**settings.json** 
`{
  "workbench.iconTheme": "material-icon-theme",
  "files.autoSave": "afterDelay",
  "editor.formatOnSave": true,
  "prettier.singleQuote": true,
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "explorer.confirmDelete": false,
  "eslint.codeAction.showDocumentation": {
    "enable": true
  },
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }
}
`

and how to copy all the existing settings for eslint extension? For, prettier I do use the extension, not the package.

**Comment by srk1195** [comment]
Just to add the previous setting, with the below eslint configuration I am able to over come my issue, ie.,  comma-dangle for functions.

`rules: {
    'comma-dangle': [
      'error',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'never',
      },
    ],
  },
`

**Comment by maximv-ngdata** [comment]
I had issues with conflicting rules about trailing comma's as well. I could fix it by removing `comma-dangle` from the eslint rules and adding this instead:

```js
rules: {
    ...
    "prettier/prettier": [
      "error",
      {
        trailingComma: "es5",
      },
    ],
  },
},
```

**Comment by chbybnwr** [comment]
@maximv-ngdata just want to mention this https://prettier.io/docs/integrating-with-linters/
