### ISSUE TITLE
Allow .eslintignore and .prettierignore

### ISSUE THREAD

**Issue by KentoMoriwaki** [wantedly/frolint#36]
## Why

Stop applying linter and formatter to auto-generated files

## What

Handle .eslintignore and .prettierignore, or other ways

**Comment by KentoMoriwaki** [comment]
@yamadayuki How do you think?

**Comment by yamadayuki** [comment]
I completely agree with that.
We can use ignorePath in both `eslint` and `prettier`. But both packages don't respect the `.xxxignore` file implicitly, so we should implement this feature with config.

```json
{
  "frolint": {
    "eslint": {
      "ignorePath": "./.eslintignore"
    },
    "prettier": {
      "ignorePath": "./.prettierignore"
    }
  }
}
```

We can implement as below (this is sample to respect `ignorePath`).

```ts
// For ESLint
const cli = new eslint.CLIEngine({
  baseConfig: {
    extends: [netEslintConfigPackage],
    settings: {
      ...reactSettings,
    },
  },
  fix: true,
  cwd,
  ignorePath: config.eslintConfig.ignorePath, // <---
});

// For Prettier
const { ignored } = await prettier.getFileInfo(
  filepath,
  {
    ignorePath: config.prettierConfig.ignorePath // <---
  }
)
```

**Comment by KentoMoriwaki** [comment]
cc @chloe463
