### ISSUE TITLE
Add wantedly_dev to NPM collaborators to eslint-plugin-wantedly

### ISSUE THREAD

**Issue by kobayang** [wantedly/frolint#863]
## Why

Failed to publish `eslint-plugin-wantedly` package with permission denined.

```
lerna http fetch PUT 403 https://registry.npmjs.org/eslint-plugin-wantedly 621ms
lerna ERR! E403 You do not have permission to publish "eslint-plugin-wantedly". Are you logged in as the correct user?
error Command failed with exit code 1.
```

## What

@yamadayuki  Please add `@wantedly_dev` to NPM collaborators in [`eslint-plugin-wantedly`](https://www.npmjs.com/package/eslint-plugin-wantedly) to maintain the package.

![Screen_Shot_2021-05-19_at_15_36_30](https://user-images.githubusercontent.com/12181179/118767245-761c6e00-b8b8-11eb-9f27-7b3d092d2444.png)

FYI: Other frolint packages include `@wantedly_dev` to NPM collaborators.

![Screen_Shot_2021-05-19_at_15_37_25](https://user-images.githubusercontent.com/12181179/118767397-a82dd000-b8b8-11eb-87bd-c283f80c2cbc.png)

**Comment by kobayang** [comment]
@yamadayuki ping

**Comment by qnighy** [comment]
@yamadayuki friendly ping

**Comment by yamadayuki** [comment]
@kobayang @qnighy Sorry for the late reply. I added the `wantedly_dev` and some maintainers in Wantedly.

![image](https://user-images.githubusercontent.com/7839872/121283975-075e8d80-c917-11eb-9c07-18becf733fe6.png)

**Comment by qnighy** [comment]
@yamadayuki thanks. Also thanks a lot for maintaining this library!

**Comment by kobayang** [comment]
@yamadayuki thanks!
